// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsdaZanerApp.Server.Data;

#nullable disable

namespace UsdaZanerApp.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240411171641_initial2")]
    partial class initial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UsdaZanerApp.Server.Data.UsdaDBObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("agg_level_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("asd_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("asd_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("begin_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("class_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("commodity_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("congr_district_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("county_ansi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("county_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("county_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("domain_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("domaincat_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("end_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("freq_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("group_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("load_time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prodn_practice_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reference_period_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("region_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sector_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("short_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state_alpha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state_ansi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state_fips_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("statisticcat_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("util_practice_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("watershed_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("watershed_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("week_ending")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("year")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zip_5")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsdaDBObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
